### ISSUE TITLE
Navigation state and guards

### ISSUE THREAD

**Issue by damianroszyk** [datorama/akita-ng-router-store#12] opened 2020-02-20 14:15 UTC
Hi, 
I have a problem when using this plugin combined with guards. 
I want to prevent navigation and route param to change with CanDeactivate ( it works as expected ) however in router store state is already changed. 
Navigation Cancel doesn't restore it to previous state.

Maybe state should be updated after Navigation End instead of start ?

Screens from the dev tools plugin:
![1](https://user-images.githubusercontent.com/12885741/74941679-b9590a00-53f3-11ea-8519-83490c3f6445.PNG)
![2](https://user-images.githubusercontent.com/12885741/74941677-b827dd00-53f3-11ea-91c5-59fda92f0106.PNG)

If you'd like stackblitz demo I can prepare but I think screens explain where is my problem

**Comment by NetanelBasal** [comment] 2020-02-20 16:43
Can you check what's the behavior in ngrx/ngxs router, please?

**Comment by damianroszyk** [comment] 2020-02-21 08:10
Hey,
I've checked NGXS ( here is a simple stackblitz https://ngxs-router-plugin-8nmr42.stackblitz.io/account/notifications ) and it seems to work the same as akita router plugin.

But it is kinda weird for me because if I want to use for example `this.routerQuery.selectParams('id')` as my source and I want to change route but guard prevented me to do so I will end up with change in my source stream but still the same url.

Am I missing something here or doing wrong ?

**Comment by NetanelBasal** [comment] 2020-02-21 08:42
There are cases where you'll be interested in the parameters regardless of whether the navigation was successful or not. I don't mind to get a PR that optionally allows your requested behavior.

**Comment by katyapavlenko** [comment] 2020-04-05 09:55
Hi, just got same problem in my project – when CanDeactivate returns false, but route params are lost

Is there any workaround until it's not fixed in akita?

**Comment by NetanelBasal** [comment] 2020-04-05 11:06
@damianroszyk, can you please create a stackblitz demo, with the exiting behavior and the required feature?

**Comment by katyapavlenko** [comment] 2020-04-06 16:31
@NetanelBasal why don't you want to subscribe only on `navigationEnd` event in the router? It would solve the issue

**Comment by katyapavlenko** [comment] 2020-04-06 19:26
Also I found issue and fix for same problem in ngxs repo: https://github.com/ngxs/store/issues/542

Checked @damianroszyk 's demo, it uses previous version of ngxs, without that fix

**Comment by NetanelBasal** [comment] 2020-04-07 04:47
@katyapavlenko I will try to get to it asap. If you want to submit a PR with the fix based on the fix [here](https://github.com/ngxs/store/pull/895/files#diff-96aa2bf67839c8810b8cab91460e8323), you're welcome.

**Comment by damianroszyk** [comment] 2020-04-07 06:41
@katyapavlenko thanks for pointing out my mistake, yes there is an old version of ngxs in my demo and it works with newer version

@NetanelBasal here is stackblitz with Akita https://stackblitz.com/edit/angular-euu9ik
It's simple but you can see that params in router store changes but route is prevented from leave

**Comment by katyapavlenko** [comment] 2020-04-07 08:13
@NetanelBasal I can try to add a PR if you can briefly explain me what you are using router hooks instead of just subscribing on event. I checked ngxs code and see that it doesn't use hooks, so I can just bring to akita-router code alike solution, but want to understand if it possibly can loose something with removing hooks

**Comment by NetanelBasal** [comment] 2020-04-07 09:32
@damianroszyk check this update: https://stackblitz.com/edit/angular-zm3p5j

**Comment by NetanelBasal** [comment] 2020-04-07 09:33
@katyapavlenko thanks, I already did it. These are the changes:

# v5.0.0
- Remove `queryParamsMap` and `paramsMap` from store.
- The new state is now in the following structure:

```typescript
ActiveRouteState = {
  url: string;
  urlAfterRedirects: string;
  fragment: string;
  params: HashMap<any>;
  queryParams: HashMap<any>;
  data: HashMap<any>;
}
```
- The state will be updated in the `resolveEnd` event. Fix [this](https://github.com/datorama/akita-ng-router-store/issues/12) issue.

**Comment by damianroszyk** [comment] 2020-04-07 09:38
@NetanelBasal great thanks!

**Comment by NetanelBasal** [comment] 2020-04-07 09:39
@damianroszyk works as expected?

**Comment by katyapavlenko** [comment] 2020-04-07 10:28
@NetanelBasal thank you a lot!
But looks like the version is not yet available on npm
```
npm i @datorama/akita-ng-router-store@5.0.0        
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @datorama/akita-ng-router-store@5.0.0
```

**Comment by NetanelBasal** [comment] 2020-04-07 10:29
Yes, I didn't publish yet. Can you confirm that this is the expected behavior? stackblitz.com/edit/angular-zm3p5j

**Comment by damianroszyk** [comment] 2020-04-07 10:32
@NetanelBasal yes it is working as expected

**Comment by katyapavlenko** [comment] 2020-04-07 10:34
@NetanelBasal yes, it's correct, also tried on my project, the bug is gone :heart"

**Comment by NetanelBasal** [comment] 2020-04-07 10:35
Done.

**Closed** 2020-04-07 10:35 UTC

**Comment by NetanelBasal** [comment] 2020-04-07 10:36
https://github.com/datorama/akita/blob/master/angular/playground/projects/ng-router-store/BREAKING_CHANGES.md
